### ISSUE TITLE
Compliments ✨ 

### ISSUE THREAD

**Issue by joe-dev-public** [fac25/Joe-Manoela-Karwan-Yassien-Authentication#64]
- Sign-up validation with user feedback 👍🏻 
- Sanitisation, no HTML/JS injection for me 😔 🧽 
- Nice SQL join in the models 🔗
- Neat/well-organised code & codebase 🧹  
- Deployed site works 😌

**Comment by modanova** [comment]
Thank you very much for the lovely comments!
